FROM python:3.8-alpine
RUN pip3 install --upgrade pip
RUN mkdir -p /todoFilesApp
COPY ./todoFilesApp /todoFilesApp
WORKDIR /todoFilesApp
RUN pip3 install -r ./requirements.txt
EXPOSE 8080
ENTRYPOINT [ "python" ]
CMD [ "-u", "todoFilesApp.py" ] 