FROM python:3.8-alpine
RUN pip3 install --upgrade pip
RUN mkdir -p /todoApp
COPY ./todoApp /todoApp
WORKDIR /todoApp
##RUN pip3 install -r ./requirements.txt
EXPOSE 8080
ENTRYPOINT [ "python" ]
CMD [ "-u", "todoApp.py" ] 